### PR TITLE
Main Menu

### PR DESCRIPTION
**Pull request by Cavekitty16**

### CODE REVIEW

**Comment by zoogies** [comment]
Some thoughts:
- Do we need the resolution or quality options? Might be extra work to implement the quality specifically, but I have no idea
- Before merging, we need to update this branch from main and then hook up the "start" to put us in either the basement scene or a new scene before that which introduces the story AND THEN goes into the basement
- Also after merging from main try to clean up the `Assets` directory, like moving the main menu and settings scripts into `Assets/Scripts`

**Comment by zoogies** [comment]
Also, it would be nice for us to have a "credits" with the names of everyone, and also a logo+title for our club

**Comment by Cavekitty16** [comment]
- Resolution seems hard but quality we would just need to go to the projects quality setting and copy settings from something else
- I think do we should introduce the story & controls after pressing start
- I will clean up the directory
- do you want credits before the story or in their own button in the main menu, and do you want the logo on the main menu or the credits

**Comment by zoogies** [comment]
> Resolution seems hard but quality we would just need to go to the projects quality setting and copy settings from something else

Feel free to research this and update, I have no idea how it works so maybe its feasible!

> I think do we should introduce the story & controls after pressing start

I can create a new task for somebody to make an "intro" scene which segways from main menu into basement (effectively a slideshow giving info as text)

> do you want credits before the story or in their own button in the main menu, and do you want the logo on the main menu or the credits

I think we should just put the logo in the corner of the main menu, and then have credits play at the end of the game with names as well as the logo again

**Comment by Daniel-Frederick** [comment]
I agree with everything Ryan mentioned above. 

> I think we should just put the logo in the corner of the main menu, and then have credits play at the end of the game with names as well as the logo again

@Cavekitty16 I want to note that the UI does not need to be perfect right now. Just put stuff in a "nice" spot for now and we can always adjust it later.

**Comment by zoogies** [comment]
I just created the intro slideshow scene ( #22 ), which you can hook up the play button to when it gets merged

**Review by zoogies — CHANGES_REQUESTED** [review]
Let me know how things are going with the other items we discussed: I'm happy to help out as needed

**Comment by zoogies** [comment]
The main blockers to merge are:
- hooking up the play button to load the intro cutscene
- removing the settings menu?
- putting the logo on?
- cleaning up the assets

**Comment by zoogies** [comment]
#22 merged, should be all ready for you to hook into

**Comment by Cavekitty16** [comment]
I don't see where the cutscene is, I hid the settings and added the logo

**Review by zoogies — APPROVED** [review]
LGTM

**Pull request merged**
